# vim: sw=2 ts=2 et :
---
# Include variable definitions
- name: "include variable overrides"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distrubition }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
  tags:
    - vagrant

# Install packages
- name: install vagrant packages
  package:
    name: "{{ vagrant_packages }}"
    state: "{{ vagrant_packages_state }}"
  become: yes
  tags:
    - vagrant
